/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */
module regfile (
  input [1:0] rs,
  input [1:0] rd,
  input [15:0] result,
  input clk,
  output [15:0] b,
  output [15:0] r0,
  output [15:0] r1,
  output [15:0] r2,
  output [15:0] r3
);
  wire [15:0] s0;
  wire [15:0] s1;
  wire [15:0] s2;
  wire [15:0] s3;
  wire s4;
  wire [15:0] r0_temp;
  wire s5;
  wire [15:0] r1_temp;
  wire s6;
  wire [15:0] r2_temp;
  wire s7;
  wire [15:0] r3_temp;
  DemuxBus2 #(
    .Bits(16),
    .Default(0)
  )
  DemuxBus2_i0 (
    .sel( rd ),
    .in( result ),
    .out_0( s0 ),
    .out_1( s1 ),
    .out_2( s2 ),
    .out_3( s3 )
  );
  Decoder2 Decoder2_i1 (
    .sel( rd ),
    .out_0( s4 ),
    .out_1( s5 ),
    .out_2( s6 ),
    .out_3( s7 )
  );
  // r0
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i2 (
    .D( s0 ),
    .C( clk ),
    .en( s4 ),
    .Q( r0_temp )
  );
  // r1
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i3 (
    .D( s1 ),
    .C( clk ),
    .en( s5 ),
    .Q( r1_temp )
  );
  // r2
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i4 (
    .D( s2 ),
    .C( clk ),
    .en( s6 ),
    .Q( r2_temp )
  );
  // r3
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i5 (
    .D( s3 ),
    .C( clk ),
    .en( s7 ),
    .Q( r3_temp )
  );
  Mux_4x1_NBits #(
    .Bits(16)
  )
  Mux_4x1_NBits_i6 (
    .sel( rs ),
    .in_0( r0_temp ),
    .in_1( r1_temp ),
    .in_2( r2_temp ),
    .in_3( r3_temp ),
    .out( b )
  );
  assign r0 = r0_temp;
  assign r1 = r1_temp;
  assign r2 = r2_temp;
  assign r3 = r3_temp;
endmodule

module DemuxBus2
#(
    parameter Bits = 2,
    parameter Default = 0 
)
(
    output [(Bits-1):0] out_0,
    output [(Bits-1):0] out_1,
    output [(Bits-1):0] out_2,
    output [(Bits-1):0] out_3,
    input [1:0] sel,
    input [(Bits-1):0] in
);
    assign out_0 = (sel == 2'h0)? in : Default;
    assign out_1 = (sel == 2'h1)? in : Default;
    assign out_2 = (sel == 2'h2)? in : Default;
    assign out_3 = (sel == 2'h3)? in : Default;
endmodule


module Decoder2 (
    output out_0,
    output out_1,
    output out_2,
    output out_3,
    input [1:0] sel
);
    assign out_0 = (sel == 2'h0)? 1'b1 : 1'b0;
    assign out_1 = (sel == 2'h1)? 1'b1 : 1'b0;
    assign out_2 = (sel == 2'h2)? 1'b1 : 1'b0;
    assign out_3 = (sel == 2'h3)? 1'b1 : 1'b0;
endmodule


module DIG_Register_BUS #(
    parameter Bits = 1
)
(
    input C,
    input en,
    input [(Bits - 1):0]D,
    output [(Bits - 1):0]Q
);

    reg [(Bits - 1):0] state = 'h0;

    assign Q = state;

    always @ (posedge C) begin
        if (en)
            state <= D;
   end
endmodule

module Mux_4x1_NBits #(
    parameter Bits = 2
)
(
    input [1:0] sel,
    input [(Bits - 1):0] in_0,
    input [(Bits - 1):0] in_1,
    input [(Bits - 1):0] in_2,
    input [(Bits - 1):0] in_3,
    output reg [(Bits - 1):0] out
);
    always @ (*) begin
        case (sel)
            2'h0: out = in_0;
            2'h1: out = in_1;
            2'h2: out = in_2;
            2'h3: out = in_3;
            default:
                out = 'h0;
        endcase
    end
endmodule



