# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param power.BramSDPPropagationFix 1
set_param power.enableUnconnectedCarry8PinPower 1
set_param power.enableCarry8RouteBelPower 1
set_param power.enableLutRouteBelPower 1
create_project -in_memory -part xczu7ev-ffvc1156-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/akshi/Add_Jmp_up/Add_Jmp_up.cache/wt [current_project]
set_property parent.project_path C:/Users/akshi/Add_Jmp_up/Add_Jmp_up.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zcu104:part0:1.1 [current_project]
set_property ip_output_repo c:/Users/akshi/Add_Jmp_up/Add_Jmp_up.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/akshi/Add_Jmp_up/Add_Jmp_up.srcs/sources_1/imports/hello/add_jump_cpu.v
  C:/Users/akshi/Add_Jmp_up/Add_Jmp_up.srcs/sources_1/imports/hello/adder_nbits.v
  C:/Users/akshi/Add_Jmp_up/Add_Jmp_up.srcs/sources_1/imports/hello/assembler.v
  C:/Users/akshi/Add_Jmp_up/Add_Jmp_up.srcs/sources_1/imports/hello/counter_with_preset.v
  C:/Users/akshi/Add_Jmp_up/Add_Jmp_up.srcs/sources_1/new/debounce_onepulse.v
  C:/Users/akshi/Add_Jmp_up/Add_Jmp_up.srcs/sources_1/imports/hello/decoder-1x8.v
  C:/Users/akshi/Add_Jmp_up/Add_Jmp_up.srcs/sources_1/imports/hello/decoder.v
  C:/Users/akshi/Add_Jmp_up/Add_Jmp_up.srcs/sources_1/imports/hello/decoder_1x4.v
  C:/Users/akshi/Add_Jmp_up/Add_Jmp_up.srcs/sources_1/imports/hello/demux_nbits.v
  C:/Users/akshi/Add_Jmp_up/Add_Jmp_up.srcs/sources_1/imports/hello/dff.v
  C:/Users/akshi/Add_Jmp_up/Add_Jmp_up.srcs/sources_1/imports/hello/eeprom.v
  C:/Users/akshi/Add_Jmp_up/Add_Jmp_up.srcs/sources_1/imports/hello/execute.v
  C:/Users/akshi/Add_Jmp_up/Add_Jmp_up.srcs/sources_1/imports/hello/mux_2x1_nbits.v
  C:/Users/akshi/Add_Jmp_up/Add_Jmp_up.srcs/sources_1/imports/hello/mux_4x1_nbits.v
  C:/Users/akshi/Add_Jmp_up/Add_Jmp_up.srcs/sources_1/imports/hello/priorityencoder3.v
  C:/Users/akshi/Add_Jmp_up/Add_Jmp_up.srcs/sources_1/new/probe_registers.v
  C:/Users/akshi/Add_Jmp_up/Add_Jmp_up.srcs/sources_1/imports/hello/regfile.v
  C:/Users/akshi/Add_Jmp_up/Add_Jmp_up.srcs/sources_1/imports/hello/fpga_top.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/akshi/vdp_level_2/vdp_level_2.srcs/constrs_1/new/ultrascale_base.xdc
set_property used_in_implementation false [get_files C:/Users/akshi/vdp_level_2/vdp_level_2.srcs/constrs_1/new/ultrascale_base.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top fpga_top -part xczu7ev-ffvc1156-2-e


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef fpga_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file fpga_top_utilization_synth.rpt -pb fpga_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
