webtalk_init -webtalk_dir C:/Users/akshi/Add_Jmp_up/Add_Jmp_up.sim/sim_1/behav/xsim/xsim.dir/tb_fpga_top_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Sep 30 21:14:33 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "7e27a89a-1f6d-49be-b1f5-8498f57ba02d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "fdd59c190105461b86a0aa8ce700d979" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "66" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 4500U with Radeon Graphics         " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2371 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "360 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "9440_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1218809486 -regid "" -xml C:/Users/akshi/Add_Jmp_up/Add_Jmp_up.sim/sim_1/behav/xsim/xsim.dir/tb_fpga_top_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/akshi/Add_Jmp_up/Add_Jmp_up.sim/sim_1/behav/xsim/xsim.dir/tb_fpga_top_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/akshi/Add_Jmp_up/Add_Jmp_up.sim/sim_1/behav/xsim/xsim.dir/tb_fpga_top_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
